kuali/rice

kns/src/main/java/org/kuali/rice/kns/web/struts/action/KualiDocumentActionBase.java

KULRICE-14041 Maint docs for business objects where notes associated with business object lose notes during ad hoc routing

KULRICE-14041 Maint docs for business objects fix for ad hoc routing

---

pom.xml
rice-framework/krad-web-framework/src/main/java/org/kuali/rice/krad/datadictionary/DefaultListableBeanFactory.java
rice-middleware/core/impl/src/main/java/org/kuali/rice/core/impl/cache/DistributedCacheManagerDecorator.java

KULRICE-14144 Re-upgrade Rice to Spring 4

KULRICE-14144 Re-upgrade Rice to Spring 4

---

db/xml/pom.xml
pom.xml
rice-framework/krad-app-framework/pom.xml
rice-framework/krad-data/pom.xml
rice-framework/krad-web-framework/pom.xml
rice-middleware/core-service/impl/pom.xml
rice-middleware/kim/kim-impl/pom.xml
rice-middleware/ksb/client-impl/pom.xml
rice-middleware/ksb/server-impl/pom.xml

Duplicate of rice-2.5 pull request https://github.com/kuali/rice/pull/8

KULRICE-14149 Added org.eclipse.persistence.oracle depencency

---

pom.xml

Revert "KULRICE-14155 Reenabled filtering of docbooks"

---

scripts/krad-conversion/src/test/resources/test.config.properties
scripts/upgrades/1.0.3 to 2.0.0/final/README.TXT
scripts/upgrades/2.0.0 to 2.1/final/README.TXT
src/site/docbook/IG/overview.xml
src/site/docbook/Intro_To_Rice/TRG_Global.xml
src/site/docbook/KSB_Guide/KSB_Bus_Security.xml
src/site/docbook/books/index.xml

Duplicate of rice-2.5 pull request #33

KULRICE-13103 Changed docbook to point to GitHub for Rice source

---

src/site/docbook/books/release-notes.xml

Duplicate of rice-2.5 pull request https://github.com/kuali/rice/pull/28

KULRICE-14146 Rice 2.5.2 Release Notes

---

pom.xml
src/site/docbook/KRAD_Guide/intro_to_uif.xml

This resolves the issue with our doc books.  Apparently, there is a problem with the intro to UIF in v2.4 through master.  Once master is fixed and verified, I will create pull requests for the other environments.

KULRICE-14155 rice 2.6 docBooks fail

---

rice-middleware/impl/src/main/java/org/kuali/rice/kew/documentoperation/web/DocumentOperationAction.java
rice-middleware/impl/src/main/java/org/kuali/rice/kew/engine/node/service/BranchService.java
rice-middleware/impl/src/main/java/org/kuali/rice/kew/engine/node/service/impl/BranchServiceImpl.java
rice-middleware/impl/src/main/java/org/kuali/rice/kim/service/impl/UiDocumentServiceImpl.java
rice-middleware/sampleapp/src/it/java/edu/sampleu/admin/workflow/DocumentOperationAft.java

Added a new helper which find the RoleMemberBo objects for a given
principal and role then updated populateRoleMembers to use it instead of
fetching all roles for the user and doing manual population of the list.

KULRICE-13136: Performance improvement on populateRoleMembers

---

pom.xml
rice-framework/krad-data/src/main/java/org/kuali/rice/krad/data/metadata/impl/DataObjectMetadataImpl.java
rice-framework/krad-data/src/test/java/org/kuali/rice/krad/data/jpa/JpaMetadataProviderTest.java
rice-middleware/core/api/src/test/groovy/org/kuali/rice/core/api/criteria/PredicateTest.groovy
rice-middleware/impl/src/test/java/org/kuali/rice/kew/rule/GenericAttributeContentTest.java
rice-middleware/ksb/client-impl/pom.xml

Maven libraries Upgrade without the groovy upgrade

KULRICE-14145 : Maven Upgrade in support of Java 8 Part 2

---

rice-framework/krad-data/src/test/java/org/kuali/rice/krad/data/jpa/JpaMetadataProviderTest.java
rice-middleware/core/api/src/test/groovy/org/kuali/rice/core/api/criteria/PredicateTest.groovy
rice-middleware/impl/src/test/java/org/kuali/rice/kew/rule/GenericAttributeContentTest.java

To fix issues introduced by pull request https://github.com/kuali/rice/pull/51.

KULRICE-14145 Made unit test independent of collection ordering.

---

rice-middleware/sampleapp/src/it/java/edu/sampleu/admin/workflow/DocumentOperationAft.java

just added wait statement to see if it fixes in ci.  Works locally.

KULRICE-14178 added wait time

---

rice-middleware/impl/src/main/java/org/kuali/rice/kew/documentoperation/web/DocumentOperationAction.java
rice-middleware/impl/src/main/java/org/kuali/rice/kew/engine/node/service/BranchService.java
rice-middleware/impl/src/main/java/org/kuali/rice/kew/engine/node/service/impl/BranchServiceImpl.java
rice-middleware/impl/src/main/java/org/kuali/rice/kim/service/impl/UiDocumentServiceImpl.java
rice-middleware/sampleapp/src/it/java/edu/sampleu/admin/workflow/DocumentOperationAft.java

Applied changes from pr #41 to 2.5

KULRICE-14035, KULRICE-13136 Applying changes to 2.5

---

rice-middleware/krms/impl/src/main/resources/org/kuali/rice/krms/datadictionary/CategoryBo.xml
rice-middleware/krms/impl/src/main/resources/org/kuali/rice/krms/datadictionary/KrmsAttributeDefinitionBo.xml

This is a 2.5 port of the commit to master https://github.com/kuali/rice/commit/19fe6e271fcea125b590a82add3ccbe0f547c710

KULRICE-13194 Added namespace drop down for KRMS Category and Attribute Lookups

---

rice-middleware/impl/src/main/java/org/kuali/rice/kew/engine/node/RouteNodeInstance.java
rice-middleware/impl/src/main/java/org/kuali/rice/kew/useroptions/UserOptionsServiceImpl.java

Merger of pull request #63 and #65

Merge UI contributions to Rice 2.5

---

README.md

Matches pull request  #82 for rice-2.5

KULRICE-14160 Created GitHub specific README.md 

---

NOTICE.txt
pom.xml

Matches pull request #60 for rice-2.5

KULRICE-14177 Update WSS4J to 1.6.18

---

rice-framework/krad-sampleapp/web/src/it/java/org/kuali/rice/krad/labs/LabsEnterKeySupportTables2Aft.java

This is a duplicate of https://github.com/kuali/rice/pull/38 for the rice-2.5 branch

KULRICE-14159 - Fix testDemoEnterKeySupportTables2 AFT

---

rice-middleware/sampleapp/src/it/java/edu/sampleu/main/CreateNewAgendaAft.java

Could not reproduce locally. Adding a 3 sec wait to allow the window to load completely before it is switched

KULRICE-14204 - AFT Failure: CreateNewAgendaAft

---

rice-tools-test/src/main/java/org/kuali/rice/testtools/selenium/WebDriverLegacyITBase.java

KULRICE-14208 AFT Failure: ResponsibilityActionListBkMrkAft

---

rice-middleware/krms/api/src/main/java/org/kuali/rice/krms/api/repository/RuleRepositoryService.java

Additional KRMS methods cached in the aid of OLE performance

KULRICE-14209 	KRMS performance analysis for OLE Circ Policies

---

rice-middleware/it/krms/src/test/java/org/kuali/rice/krms/test/ValidationIntegrationTest.java
rice-middleware/krms/impl/src/main/java/org/kuali/rice/krms/impl/repository/RuleBo.java

Re-factored test ValidationIntegrationTest.java & corrected possible infinite loop in RuleBo.java.  Added inverted tests to test for issues of negative feedback on tests.

KULRICE-14209 KRMS performance analysis for OLE Circ Policies

---

rice-middleware/impl/src/main/java/org/kuali/rice/kew/actionrequest/service/impl/ActionRequestServiceImpl.java

ActionRequestServiceImpl.deleteActionRequestGraph will now only delete
an associated ActionTaken if it is the only ActionRequest associated
with the ActionTaken.

KULRICE-14188

---

rice-middleware/impl/src/main/java/org/kuali/rice/kim/service/impl/UiDocumentServiceImpl.java

Based off https://github.com/kuali/rice/pull/114 
Also removed unused imports.

KULRICE-14229 Optimistic locking issue when adding role delegate member

---

doc/src/main/docbook/release-notes.xml

KULRICE-14214 1.0.7 release notes

---

api/pom.xml
doc/pom.xml
impl/pom.xml
kcb/pom.xml
ken/pom.xml
kew/pom.xml
kim/pom.xml
kns/pom.xml
ksb/pom.xml
pom.xml
sampleapp/pom.xml
web/pom.xml

Merge when the release has been verified.

KULRICE-14214 prepare for next development iteration

---

rice-middleware/impl/src/main/java/org/kuali/rice/kim/service/impl/UiDocumentServiceImpl.java
rice-middleware/kim/kim-impl/src/main/java/org/kuali/rice/kim/impl/common/delegate/DelegateTypeBo.java

It looks like a lot of changes to getDelegationMembers, but it is mostly formatting changes.   I will comment below in the code on the lines that were added or removed.

KULRICE-14235 - KIM Role: Delegate issues once the member is inactivated

---

db/sql/src/main/resources/org/kuali/rice/rice-sql/upgrades/2.6.0/mysql/server/demo/2015-05-11-KULRICE--14337.sql
db/sql/src/main/resources/org/kuali/rice/rice-sql/upgrades/2.6.0/oracle/server/demo/2015-05-11-KULRICE--14337.sql

data required for rice-rest tests.

KULRICE-14237 Setup CI testing for RICE-REST, demo data setup

---

web/src/main/webapp/kr/WEB-INF/jsp/KualiLookup.jsp

Duplicate of pull the following pull requests:
master - #141
2.3 - #142

KULRICE-14248 - fix for document help icon of Document Search

---

src/site/docbook/books/release-notes.xml

The generated release notes can be found in https://jira.kuali.org/browse/KULRICE-14250

KULRICE-14250 Rice 2.5.3 release notes.

---

rice-middleware/it/krms/src/test/java/org/kuali/rice/krms/test/ValidationIntegrationTest.java
rice-middleware/krms/api/src/main/java/org/kuali/rice/krms/api/repository/RuleRepositoryService.java

Added instructions to reapply changes to https://jira.kuali.org/browse/KULRICE-14209 .
Diff showing what has changed since 2.3.6 release:
https://github.com/cniesen/rice/compare/e439123107e527e27c11b46eccf21622372691f8...cniesen:rice-2.3

Rollback for a slim 2.3.7 release

---

src/site/docbook/books/release-notes.xml

Generated release note sample is attached to the jira.

KULRICE-14250 Rice 2.1.10 release notes.

---

rice-framework/krad-web-framework/src/main/java/org/kuali/rice/krad/web/filter/UserLoginFilter.java
rice-framework/krad-web-framework/src/main/java/org/kuali/rice/krad/web/listener/KualiHttpSessionListener.java

[RESKC-432] Pessimistic lock release on log out or session expiration fix

---

src/site/docbook/books/release-notes.xml

Generated release note sample is attached to the jira.

KULRICE-14250 Rice 2.3.7 release notes.

---

api/pom.xml
doc/pom.xml
impl/pom.xml
kcb/pom.xml
ken/pom.xml
kew/pom.xml
kim/pom.xml
kns/pom.xml
ksb/pom.xml
pom.xml
sampleapp/pom.xml
web/pom.xml

update versions to 1.0.8-Snapshot, update kuali-commons to 1.7.6

KULRICE-14250 update versions to 1.0.8-Snapshot, update kuali-commons to 1.7.6

---

db/sql/src/main/resources/org/kuali/rice/rice-sql/upgrades/2.6.0/mysql/server/demo/2015-05-20-KULRICE--833.sql
db/sql/src/main/resources/org/kuali/rice/rice-sql/upgrades/2.6.0/oracle/server/demo/2015-05-20-KULRICE--833.sql
rice-middleware/impl/src/main/java/org/kuali/rice/kew/engine/RouteHelper.java
rice-middleware/impl/src/main/java/org/kuali/rice/kew/engine/node/XPathSplitNode.java
rice-middleware/sampleapp/src/it/resources/XPathSplitNodeEDLExample/01-XPathSplitNode_RuleTemplates.xml
rice-middleware/sampleapp/src/it/resources/XPathSplitNodeEDLExample/02-XPathSplitNode_Doctype.xml
rice-middleware/sampleapp/src/it/resources/XPathSplitNodeEDLExample/03-XPathSplitNode_Rules.xml
rice-middleware/sampleapp/src/it/resources/XPathSplitNodeEDLExample/04-XPathSplitNode_Edl.xml
src/site/docbook/KEW_Guide/KEW_Defs.xml

The example eDocLite has been added to the sample application using SQL.    I tested using Oracle and Mysql to verify the SQL is correct for both.

KULRICE-833 - Implement a Split Node which operates using XPath

---

rice-middleware/sampleapp/src/it/java/edu/sampleu/admin/CampusActionListAftBase.java
rice-middleware/sampleapp/src/it/java/edu/sampleu/admin/CampusAftBase.java

These errors are due to the campus primary key being only two characters so it is more difficult to get a random unique primary key. I changed it so that it sets the campus to a number and a letter, which I think make things a bit easier. It's what I always do when I'm trying to create a campus locally to avoid creating one that already exists. I also made the while loop that attempts to get a unique primary key faster (avoided using xpath) and made the number of attempts 10 instead of 3. I think the combination of these changes will make this test less volatile.
If these changes do not fix the occasional problems we are seeing, I think we could use another document besides the campus document. It seems like most of the test are not testing the campus functionality, instead they are …

KULRICE-14256 - Investigate CampusActionListBkMrkAft failures

---

rice-middleware/kew/api/pom.xml
rice-middleware/kew/api/src/main/java/org/kuali/rice/kew/api/document/Document.java
rice-middleware/kew/api/src/main/java/org/kuali/rice/kew/api/util/UserTextFilterForXml.java
rice-middleware/kew/api/src/test/groovy/org/kuali/rice/kew/api/util/UserTextFilterForXmlTest.java

Added UserTextFilterForXml to remove invalid XML characters from document titles/attributes (and potentially other user-entered fields).

KULRICE-14257

---

rice-middleware/sampleapp/src/it/java/edu/sampleu/main/AgendaEditorAndOrToggleSyncAft.java

Spilt up the tests since they are each long and seem to be timing out.

KULRICE-14258 - Failing AFTs in 2.6

---

rice-middleware/sampleapp/src/it/java/edu/sampleu/admin/CampusActionListAftBase.java
rice-middleware/sampleapp/src/it/java/edu/sampleu/admin/CampusAftBase.java

These problems all go back to the primary key for the campus document only being 2 characters.  I've added some additional checks to prevent any problems.

KULRICE-14256	- Investigate CampusActionListBkMrkAft failures

---

rice-tools-test/src/main/java/org/kuali/rice/testtools/selenium/WebDriverHighlightHelper.java
rice-tools-test/src/main/java/org/kuali/rice/testtools/selenium/WebDriverUtils.java

A rather trivial extraction of the highlighting functionality out of WebDriverUtils to WebDriverHighlightHelper for easier reuse here at UH.  Tested locally.

Extract Highlighting from WebDriverUtils to WebDriverHighlightHelper.

---

rice-middleware/kns/src/main/java/org/kuali/rice/kns/web/struts/action/KualiExceptionHandlerAction.java

Move sensitive data from the Incident form to the user session when mode is production.  The formatting isn't displaying correctly in github, but is correct in the IDE.

Kulrice 14274

---

kns/src/main/java/org/kuali/rice/kns/web/struts/action/KualiExceptionHandlerAction.java

Incident Page exposes stack trace and allows tampering of incident emails

KULRICE-14274 Incident Page exposes stack trace

---

rice-middleware/impl/src/main/java/org/kuali/rice/kew/routeheader/DocumentRouteHeaderValue.java
rice-middleware/it/kew/src/test/java/org/kuali/rice/kew/routeheader/RouteHeaderServiceTest.java

Rice 2.5 - RICE-22 NPE from DocumentRouteHeaderValue.getRoutedByDisplayName

---

rice-middleware/kim/kim-impl/src/main/java/org/kuali/rice/kim/impl/role/RoleServiceImpl.java

…converted by the role type of the nested role and note the owning role
This issue was introduced by the following jira https://jira.kuali.org/browse/KULRICE-11579
And in the following commit https://github.com/kuali/rice/commit/0faaf0248403c3053763b2485a869660ad6a4f2a#diff-d8729e05d64c0e986678ba7bbd6b4416
It seems like it was perhaps an unintentional bug introduced by that particular change since that original jira was trying to add a new method for checking the qualified members in a backward compatible fashion.

RICE-24 nested role qualification bug

---

pom.xml
rice-framework/krad-sampleapp/web/src/main/webapp/WEB-INF/web.xml
rice-framework/krad-web-framework/src/main/java/org/kuali/rice/krad/uif/UifParameters.java
rice-framework/krad-web-framework/src/main/java/org/kuali/rice/krad/web/form/UifFormBase.java
rice-framework/krad-web/src/main/webapp/WEB-INF/web.xml
rice-framework/krad-web/src/main/webapp/krad/WEB-INF/ftl/components/group/backdoorLoginGroup.ftl
rice-framework/krad-web/src/main/webapp/krad/WEB-INF/ftl/lib/csrfToken.ftl
rice-framework/krad-web/src/main/webapp/krad/WEB-INF/ftl/lib/form.ftl
rice-framework/krad-web/src/main/webapp/krad/WEB-INF/ftl/lib/krad.ftl
rice-framework/krad-web/src/main/webapp/krad/scripts/krad.request.js
rice-middleware/kns/src/main/java/org/kuali/rice/kns/web/struts/action/KualiRequestProcessor.java
rice-middleware/web/pom.xml
rice-middleware/web/src/main/webapp/WEB-INF/Owasp.CsrfGuard.properties
rice-middleware/web/src/main/webapp/WEB-INF/jsp/dummy_login.jsp
rice-middleware/web/src/main/webapp/WEB-INF/tags/kr/page.tag
rice-middleware/web/src/main/webapp/WEB-INF/tags/rice-portal/immutableBar.tag
rice-middleware/web/src/main/webapp/WEB-INF/web.xml
rice-middleware/web/src/main/webapp/kew/WEB-INF/jsp/ActionList/ActionList.jsp
rice-middleware/web/src/main/webapp/kew/WEB-INF/jsp/DocHandlerButtons.jsp
rice-middleware/web/src/main/webapp/kew/WEB-INF/jsp/Feedback.jsp
rice-middleware/web/src/main/webapp/kew/WEB-INF/jsp/documentoperation/DocumentOperation.jsp
rice-middleware/web/src/main/webapp/kew/WEB-INF/jsp/notes/AllNotesReport.jsp
rice-middleware/web/src/main/webapp/kim/WEB-INF/jsp/dataIntegrity.jsp
rice-middleware/web/src/main/webapp/kr/WEB-INF/jsp/TextArea.jsp
rice-middleware/web/src/main/webapp/kr/WEB-INF/jsp/tldHeader.jsp
rice-middleware/web/src/main/webapp/ksb/WEB-INF/jsp/bus/ServiceBus.jsp
rice-middleware/web/src/main/webapp/ksb/WEB-INF/jsp/javasecurity/JavaSecurityManagement.jsp
rice-middleware/web/src/main/webapp/ksb/WEB-INF/jsp/messagequeue/MessageEntry.jsp
rice-middleware/web/src/main/webapp/ksb/WEB-INF/jsp/messagequeue/MessageQueue.jsp
rice-middleware/web/src/main/webapp/ksb/WEB-INF/jsp/registry/ServiceRegistry.jsp

Implemented CSRF protection across both the KNS and KRAD frameworks as well as various built-in Kuali Rice screens.

Rice 2.5 RICE-30 CSRF

---

rice-framework/krad-web-framework/src/main/resources/org/kuali/rice/krad/config/KRADSpringBeans.xml
rice-middleware/core/impl/src/main/java/org/kuali/rice/core/impl/encryption/DemonstrationGradeEncryptionServiceImpl.java
rice-middleware/core/impl/src/main/java/org/kuali/rice/core/impl/encryption/EncryptionServiceImpl.java
rice-middleware/core/impl/src/main/java/org/kuali/rice/core/impl/encryption/EncryptionStrategy.java
rice-middleware/core/impl/src/test/java/org/kuali/rice/core/impl/encryption/EncryptionServiceImplTest.java

Implemented a new encryption service that can be configured (via rice configuration) to use either DES or DESede.

Rice 2.5 rice 11 encryption service
